// // two tpyes of data types
// //1. primitve
//            /* Number
//             BigInt
//             String
//             Boolean
//             Symbol
//             null
//             undefined */

// //2. non-primitve
//         /* Array
//          Object
//          function*/
          

// /*let num =1 ;
// let num2 =2; 

// console.log( "num",num,num2);

// let name = "gaurav";
// let name2="kindarkhediya";
// console.log("names:",name,name2);

// // boolean
// let isTrue=true;
// let isFalse=false;

// console.log("boolean",isTrue);

// // undefine 

// let a;
// console.log("undefine :" ,a);

// let BigInt=1234567891655n;
// console.log(BigInt);

// // 2. non primitive

// // object 
// let Student = {
//     name : "gaurav",
//     roll:77,
//     address:{
//         city:"jnd",
//     }
// }
// console.log(Student)
 
// // array 


// let c=[1,2,3,4,5,6,7,8,9];
// let student={

// };

// let arrOfstud=[{},{}];
// console.log(c);
// */
// /*
// function greet() {
//     console.log("this is function");

// }
// greet();

// function showValues(value){
//     console.log("thi is value",value);
//     if (value==20){
//         console.log("number------");
//     }
// }

// showValues();
// showValues(20);
// showValues([1,2,3,4]);
// showValues()
// */

// // adition 
// /*let a;
// let b;
// function add(a,b){
//     return a+b ;
// }
//  console.log("adition is ",add(10,20));

//  function sub(a,b){
//     return a-b ;
// }
//  console.log("subs. is ",sub(20,10));

//  function mult(a,b){
//     return a*b ;
// }
//  console.log("multi. is ",mult(20,10));

//  function div(a,b){
//     return a/b ;
// }
//  console.log("div. is ",div(100,10));


// add();
// const add1 =(x,y)=> {
//     return x+y 
// }


// const sub1 =(x,y)=> {
//     return x-y 
// }
// console.log ('this is arrow function',sub1(40,30),add(10,20))

// const mult1 =(x,y)=> {
//     return x*y 
// }
// console.log ('this is arrow function',mult1(40,30))

// const div1 =(x,y)=> {
//     return x/y 
// }
// console.log ('this is arrow function',div1(4000000,40))*/

// /*let value =10;
// console .log (value);

// value -=5;
// console.log(value);

// value *=5;
// console.log(value);

// value +=5;
// console.log(value);

// value /=5;
// console.log(value);*/

// let age=20;
// let hasId=true
// let name= "students"

// console.log("logical AND(&&)",age>18 && hasId);
// console.log("logical OR(||)",age> 18 || hasId);
// console.log("logical NOT(!)", !hasId);

// console.log(typeof age )
// console.log(typeof hasId )
// console.log(typeof name )
// console.log(typeof obj )


let value =10;
let num ="10"

console.log("value == num :", value == num);
console.log("value == num :", value === num);
console.log("value == num :", value != num);